project_name = "flexflow"
testsuite_macro = "FF_TEST_SUITE"
namespace_name = "FlexFlow"
header_extension = ".h"
doxygen = true
build_tool = "ninja"
cuda_launch_cmd = [
  "nixGL",
  "--",
]
layout_ignore_paths = [
  "lib/kernels",
  "lib/utils/test/common",
  "lib/compiler/ffi",
  "lib/op-attrs/ffi",
  "lib/pcg/ffi",
  "lib/substitutions/ffi",
  "lib/utils/ffi",
  "lib/ffi",
  "lib/utils/include/utils/graph/docs",
  "lib/compiler/test/src/internal",
  "lib/local-execution/test/src/internal",
  "bin/protobuf-to-json",
  "lib/realm-execution/src/realm-execution/redops/cuda",
]
test_case_timeout_seconds = 300
benchmark_timeout_seconds = 60
ci_benchmark_within_percent_requirement = 15

[targets.utils]
type = "lib"
has-cpu-only-tests = true
has-cpu-only-benchmarks = true
has-cuda-tests = false
has-cuda-benchmarks = false

[targets.op-attrs]
type = "lib"
has-cpu-only-tests = true
has-cpu-only-benchmarks = false
has-cuda-tests = false
has-cuda-benchmarks = false

[targets.kernels]
type = "lib"
has-cpu-only-tests = true
has-cpu-only-benchmarks = false
has-cuda-tests = true
has-cuda-benchmarks = false

[targets.pcg]
type = "lib"
has-cpu-only-tests = true
has-cpu-only-benchmarks = false
has-cuda-tests = false
has-cuda-benchmarks = false

[targets.substitutions]
type = "lib"
has-cpu-only-tests = true
has-cpu-only-benchmarks = true
has-cuda-tests = false
has-cuda-benchmarks = false

[targets.compiler]
type = "lib"
has-cpu-only-tests = true
has-cpu-only-benchmarks = true
has-cuda-tests = false
has-cuda-benchmarks = false

[targets.substitution-generator]
type = "lib"
has-cpu-only-tests = true
has-cpu-only-benchmarks = false
has-cuda-tests = false
has-cuda-benchmarks = false

[targets.task-spec]
type = "lib"
has-cpu-only-tests = true
has-cpu-only-benchmarks = false
has-cuda-tests = false
has-cuda-benchmarks = false

[targets.local-execution]
type = "lib"
has-cpu-only-tests = true
has-cpu-only-benchmarks = false
has-cuda-tests = true
has-cuda-benchmarks = false

[targets.realm-execution]
type = "lib"
has-cpu-only-tests = true
has-cpu-only-benchmarks = false
has-cuda-tests = true
has-cuda-benchmarks = false

[targets.models]
type = "lib"
has-cpu-only-tests = true
has-cpu-only-benchmarks = false
has-cuda-tests = false
has-cuda-benchmarks = false

[targets.compile-model]
type = "bin"
cuda = false

[targets.export-model-arch]
type = "bin"
cuda = false

[targets.substitution-to-dot]
type = "bin"
cuda = false

[targets.sp-ization-benchmarking]
type = "bin"
cuda = false

[targets.run-model]
type = "bin"
cuda = false

[[benchmarks.utils]]
name = "transitive_reduction"
budget = 370_000_000

[[benchmarks.utils]]
name = "transitive_closure"
budget = 470_000_000

[[benchmarks.utils]]
name = "contains_for_set"
budget = 3_500_000

[[benchmarks.utils]]
name = "transform_set"
budget = 7_000_000

[[benchmarks.utils]]
name = "try_at_for_map"
budget = 750_000

[[benchmarks.utils]]
name = "try_at_for_unordered_map"
budget = 175_000

[[benchmarks.utils]]
name = "try_merge_nondisjoint_maps"
budget = 8_000_000

[[benchmarks.utils]]
name = "try_merge_nondisjoint_bidicts"
budget = 15_000_000

[[benchmarks.utils]]
name = "query_set_allowed_values"
budget = 40_000

[[benchmarks.utils]]
name = "query_set_apply_query_to_set"
budget = 12_000_000

[[benchmarks.utils]]
name = "query_set_apply_query_to_vector"
budget = 6_000_000

[[benchmarks.utils]]
name = "get_open_kwarg_dataflow_subgraph_incoming_edges_unlabelled"
budget = 800_000

[[benchmarks.utils]]
name = "get_open_kwarg_dataflow_subgraph_incoming_edges_labelled"
budget = 800_000

[[benchmarks.utils]]
name = "get_all_open_kwarg_dataflow_edges_unlabelled"
budget = 8_200_000

[[benchmarks.utils]]
name = "get_all_open_kwarg_dataflow_edges_labelled"
budget = 8_200_000

# [[benchmarks.substitutions]]
# name = "find_pattern_matches_large"
# budget = currently times out

[[benchmarks.substitutions]]
name = "find_pattern_matches_medium"
budget = 66_000_000

[[benchmarks.substitutions]]
name = "find_pattern_matches_small"
budget = 2_800_000

[[benchmarks.substitutions]]
name = "apply_substitution"
budget = 35_000_000

[[benchmarks.compiler]]
name = "get_computation_graph_series_parallel_decomposition_on_split_test"
budget = 81_000_000

[[benchmarks.compiler]]
name = "get_computation_graph_series_parallel_decomposition_on_transformer"
budget = 4_700_000_000

[[benchmarks.compiler]]
name = "get_computation_graph_series_parallel_decomposition_on_inception_v3"
budget = 7_000_000_000

# default_build_targets = [
#   "utils",
# ]

# default_test_targets = [
#   "utils",
# ]

# default_benchmark_targets = [
#   "utils",
# ]

[cmake_flags_extra]
CMAKE_CUDA_ARCHITECTURES = "60"
