set(SPUTNIK_ROOT ${CMAKE_SOURCE_DIR}/deps/sputnik)
set(CUDA_ARCHS ${FF_CUDA_ARCH})
message(STATUS "SPUTNIK CUDA_ARCHS: ${CUDA_ARCHS}")
add_subdirectory(${SPUTNIK_ROOT})
list(APPEND FLEXFLOW_INCLUDE_DIRS 
  ${SPUTNIK_ROOT})
list(APPEND FLEXFLOW_EXT_LIBRARIES sputnik)
